import React from "react";

const InitialList = [
  //Spacecraft
  {
    id: 1,
    code: "HBA",
    definition: "Black anodized plating",
    company: "Spacecraft",
    series: "SCPB",
  },
  {
    id: 2,
    code: "027",
    definition: "Conductive black zinc cobalt plating",
    company: "Spacecraft",
    series: "SCPB",
  },
  {
    id: 3,
    code: "005",
    definition: "Black anodized plating",
    company: "Spacecraft",
    series: "SCPB",
  },
  {
    id: 4,
    code: "F80",
    definition: "Crimp plated contacts",
    company: "Spacecraft",
    series: "SCPB",
  },
  {
    id: 5,
    code: "A95",
    definition: "Gold plated contacts",
    company: "Spacecraft",
    series: "SCPB",
  },

  //AB Conn
  {
    id: 6,
    code: "M11",
    definition: "Zinc cobalt olive drab",
    company: "AB Conn",
    series: "ABCIR",
  },
  {
    id: 7,
    code: "M115",
    definition: "Zinc cobalt olive drab",
    company: "AB Conn",
    series: "ABCIR",
  },
  {
    id: 8,
    code: "M133",
    definition: "Countersunk imperial holes",
    company: "AB Conn",
    series: "ABCIR",
  },
  {
    id: 9,
    code: "M134",
    definition: "Black epoxy varnish",
    company: "AB Conn",
    series: "ABCIR",
  },
  {
    id: 10,
    code: "M14",
    definition: "Connector with size 16 AWG contact buckets",
    company: "AB Conn",
    series: "ABCIR",
  },
  {
    id: 11,
    code: "M141",
    definition: "Connector with size 22 AWG contact buckets",
    company: "AB Conn",
    series: "ABCIR",
  },
  {
    id: 12,
    code: "M145",
    definition: "M32 and M52",
    company: "AB Conn",
    series: "ABCIR",
  },
  {
    id: 13,
    code: "M263",
    definition: "Stainless Steel",
    company: "AB Conn",
    series: "ABCIR",
  },
  {
    id: 14,
    code: "M253",
    definition: "Stainless Steel",
    company: "AB Conn",
    series: "ABCIR",
  },
  {
    id: 15,
    code: "M32",
    definition: "Black zinc cobalt and through MTG holes",
    company: "AB Conn",
    series: "ABCIR",
  },
  {
    id: 16,
    code: "M34",
    definition: "Black zinc cobalt ",
    company: "AB Conn",
    series: "ABCIR",
  },
  {
    id: 17,
    code: "P3",
    definition: "Gold plated contacts",
    company: "AB Conn",
    series: "ABCIR",
  },
  {
    id: 18,
    code: "V0",
    definition: "Without contacts",
    company: "AB Conn",
    series: "ABCIR",
  },
  {
    id: 19,
    code: "C4",
    definition: "SIZE 16 CONTACT WITH A 12-14 AWG BUCKET (3626) CONTACT",
    company: "AB Conn",
    series: "ABCIR",
  },

  //Veam

  {
    id: 20,
    code: "T10",
    definition: "Heavy gold over nickel plated contacts",
    company: "ITT Veam",
    series: "CIR",
  },
  {
    id: 21,
    code: "T12",
    definition: "Standard Gold over Nickel Plating",
    company: "ITT Veam",
    series: "CIR",
  },
  {
    id: 27,
    code: "T112",
    definition: "Heavy Gold over Nickel Plating",
    company: "ITT Veam",
    series: "CIR",
  },
  {
    id: 22,
    code: "T89",
    definition:
      "Black hard coat anodized on machined parts, T68 Electrodeposited black epoxy urethane paint on casted",
    company: "ITT Veam",
    series: "CIR",
  },
  {
    id: 23,
    code: "T96",
    definition:
      "Black hard coat anodized on machined parts, T68 Electrodeposited black epoxy urethane paint on casted",
    company: "ITT Veam",
    series: "CIR",
  },
  {
    id: 24,
    code: "T96",
    definition:
      "Black hard coat anodized on machined parts, T68 Electrodeposited black epoxy urethane paint on casted",
    company: "ITT Veam",
    series: "CIR",
  },
  {
    id: 25,
    code: "T100",
    definition: "Green zinc cobalt finish",
    company: "ITT Veam",
    series: "CIR",
  },
  {
    id: 26,
    code: "T103",
    definition:
      "T89 Hard anodized on machined parts, T108 black zinc cobalt on cast parts, T112 heavy gold plated contacts",
    company: "ITT Veam",
    series: "CIR",
  },
  {
    id: 28,
    code: "T105",
    definition: "Green zinc cobalt finish, T112 heavy gold plated contacts",
    company: "ITT Veam",
    series: "CIR",
  },
  {
    id: 29,
    code: "T108",
    definition:
      "Black zinc/Iron, replaced by: T105 Green zinc cobalt finish, T112 heavy gold plated contacts",
    company: "ITT Veam",
    series: "CIR",
  },
  {
    id: 30,
    code: "T109",
    definition: "Black zinc cobalt finish, T112 heavy gold plated contacts",
    company: "ITT Veam",
    series: "CIR",
  },
  {
    id: 31,
    code: "T113",
    definition:
      "T89 Black hard coat anodized on machined parts, T68 Electrodeposited black epoxy urethane paint on casted, T112 heavy gold contacts",
    company: "ITT Veam",
    series: "CIR",
  },
  {
    id: 32,
    code: "T103",
    definition:
      "T89 Black hard black anodized on machined parts, T108 black zinc cobalt, T112 heavy gold contacts",
    company: "ITT Veam",
    series: "CIR",
  },
  {
    id: 33,
    code: "T117",
    definition:
      "T89 Black hard black anodized on machined parts, T108 black zinc cobalt, T12 gold contacts",
    company: "ITT Veam",
    series: "CIR",
  },
  {
    id: 34,
    code: "T118",
    definition:
      "T89 Black hard black anodized on machined parts, T108 black zinc cobalt, T9 silver contacts",
    company: "ITT Veam",
    series: "CIR",
  },
  {
    id: 35,
    code: "T120",
    definition: "Ecogreen 500 - cadmium free",
    company: "ITT Veam",
    series: "CIR",
  },
  {
    id: 36,
    code: "A34",
    definition:
      "Electroless nickel hardware, RoHS compliant (European version)",
    company: "ITT Cannon",
    series: "CA Reverse Bayonet or 5015 Threaded",
  },
  {
    id: 37,
    code: "A71",
    definition: "Electroless nickel hardware (U.S. version RoHS compliant)",
    company: "ITT Cannon",
    series: "CA Reverse Bayonet or 5015 Threaded",
  },
  {
    id: 38,
    code: "A206",
    definition: "Black zinc cobalt hardware (U.S. version, RoHS compliant)",
    company: "ITT Cannon",
    series: "CA Reverse Bayonet or 5015 Threaded",
  },
  {
    id: 39,
    code: "A232",
    definition: "Black zinc cobalt hardware (European version, RoHS compliant)",
    company: "ITT Cannon",
    series: "CA Reverse Bayonet or 5015 Threaded",
  },
  {
    id: 40,
    code: "A233",
    definition: "Green Zinc Cobalt",
    company: "ITT Cannon",
    series: "CA Reverse Bayonet or 5015 Threaded",
  },
  {
    id: 41,
    code: "A408",
    definition: "Extended Life Contact - Gold over Nickel",
    company: "ITT Cannon",
    series: "CA Reverse Bayonet or 5015 Threaded",
  },
  {
    id: 42,
    code: "F42",
    definition: "Less grommet and backshell",
    company: "ITT Cannon",
    series: "CA Reverse Bayonet or 5015 Threaded",
  },
  {
    id: 43,
    code: "F85",
    definition: "Less grommet and compression ring",
    company: "ITT Cannon",
    series: "CA Reverse Bayonet or 5015 Threaded",
  },
  {
    id: 44,
    code: "08",
    definition: "At end of part number calls out 90 deg backshell",
    company: "ITT Cannon",
    series: "CA Reverse Bayonet or 5015 Threaded",
  },

  //FRITS GLENAIR
  {
    id: 45,
    code: "B0",
    definition: "Connector Less Contacts",
    company: "Glenair",
    series: "FRITS",
  },
  {
    id: 46,
    code: "B1",
    definition: "Gold Plated Contacts",
    company: "Glenair",
    series: "FRITS",
  },
  {
    id: 47,
    code: "FM25",
    definition: "Backshell with Female, M25 threads, Spacecraft code M25X1.5",
    company: "Glenair",
    series: "FRITS",
  },
  {
    id: 48,
    code: "N485",
    definition: "This is the same as the PHM class, see SCPBH00-24-28P-F0-N485",
    company: "Glenair",
    series: "FRITS",
  },
  {
    id: 49,
    code: "F6",
    definition: "Aluminum / Black Electrodeposited Paint",
    company: "Glenair",
    series: "FRITS",
  },
  {
    id: 50,
    code: "F7",
    definition: "Aluminum/ Black Zinc Nickel",
    company: "Glenair",
    series: "FRITS",
  },
  {
    id: 51,
    code: "F11",
    definition: "Aluminum / Electroless Nickel",
    company: "Glenair",
    series: "FRITS",
  },
  {
    id: 52,
    code: "MB",
    definition: "Marine Bronze / Unplated",
    company: "Glenair",
    series: "FRITS",
  },
  {
    id: 53,
    code: "FK",
    definition: "Stainless Steel/ Passivate",
    company: "Glenair",
    series: "FRITS",
  },
  {
    id: 54,
    code: "G10",
    definition: "Silver Plated Contact",
    company: "Glenair",
    series: "Contact 10-",
  },
  {
    id: 55,
    code: "G117",
    definition: "Heavy Gold Plated Contact",
    company: "Glenair",
    series: "Contact 10-",
  },

  {
    id: 56,
    code: "B20",
    definition: "Hard coat black anodized",
    company: "Glenair",
    series: "Contact 10-",
  },
  //Amphenol GTC
  {
    id: 57,
    code: "C10",
    definition: "8 AWG contact for use with 10-12 AWG wire",
    company: "Glenair",
    series: "Contact 10-",
  },
  {
    id: 58,
    code: "B30",
    definition: "Gold 30u over Nickel…heavy -142 gold plated contacts",
    company: "Glenair",
    series: "Contact 10-",
  },
  {
    id: 59,
    code: "G96",
    definition: "Black Anodized",
    company: "Glenair",
    series: "Contact 10-",
  },
  {
    id: 60,
    code: "A31",
    definition: "Standard Gold",
    company: "Glenair",
    series: "Contact 10-",
  },
  //Cannon VG/Ca Bayonet
  {
    id: 61,
    code: "01",
    definition: "Metric crimp contacts",
    company: "ITT Cannon",
    series: "Cannon VG/CA Bayonet",
  },
  {
    id: 62,
    code: "02",
    definition: "Adaptor for heat shrink boots AWG crimp contacts",
    company: "ITT Cannon",
    series: "Cannon VG/CA Bayonet",
  },
  {
    id: 63,
    code: "03",
    definition: "adaptor for shrink boots, metric contacts",
    company: "ITT Cannon",
    series: "Cannon VG/CA Bayonet",
  },
  {
    id: 64,
    code: "04",
    definition: "rear mount, threat in flange, metric crimp contacts (CA3102)",
    company: "ITT Cannon",
    series: "Cannon VG/CA Bayonet",
  },
  {
    id: 65,
    code: "05",
    definition: "Rear mount, through MTG holes",
    company: "ITT Cannon",
    series: "Cannon VG/CA Bayonet",
  },
  {
    id: 66,
    code: "06",
    definition:
      "Shrink boot adaptor, threaded holes in flange, solder contacts",
    company: "ITT Cannon",
    series: "Cannon VG/CA Bayonet",
  },
  {
    id: 67,
    code: "08",
    definition: "90 degree backshell, through MTG holes",
    company: "ITT Cannon",
    series: "Cannon VG/CA Bayonet",
  },
  {
    id: 68,
    code: "09",
    definition: "90 degree backshell, through holes in flange",
    company: "ITT Cannon",
    series: "Cannon VG/CA Bayonet",
  },

  {
    id: 69,
    code: "13",
    definition: "shielded, solder contacts",
    company: "ITT Cannon",
    series: "Cannon VG/CA Bayonet",
  },
  {
    id: 70,
    code: "14",
    definition: "shielded, metric crimp contacts",
    company: "ITT Cannon",
    series: "Cannon VG/CA Bayonet",
  },
  {
    id: 71,
    code: "15",
    definition: "shielded crimp contacts",
    company: "ITT Cannon",
    series: "Cannon VG/CA Bayonet",
  },
  {
    id: 72,
    code: "41",
    definition: "shielded version, heat shrink boot adaptor",
    company: "ITT Cannon",
    series: "Cannon VG/CA Bayonet",
  },
  {
    id: 73,
    code: "109",
    definition: "Rear mount, crimp contacts, threaded MTG holes",
    company: "ITT Cannon",
    series: "Cannon VG/CA Bayonet",
  },
  {
    id: 74,
    code: "111",
    definition: "Rear mount, solder contacts, threaded MTG holes",
    company: "ITT Cannon",
    series: "Cannon VG/CA Bayonet",
  },
  {
    id: 75,
    code: "13",
    definition: "shielded, solder contacts",
    company: "ITT Cannon",
    series: "Cannon VG/CA Bayonet",
  },
];

export default InitialList;
